//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vx_sdk_config_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vx_sdk_config_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vx_sdk_config_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vx_sdk_config_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VivoxCoreInstancePINVOKE.delete_vx_sdk_config_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int num_codec_threads {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_num_codec_threads_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_num_codec_threads_get(swigCPtr);
      return ret;
    } 
  }

  public int num_voice_threads {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_num_voice_threads_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_num_voice_threads_get(swigCPtr);
      return ret;
    } 
  }

  public int num_web_threads {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_num_web_threads_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_num_web_threads_get(swigCPtr);
      return ret;
    } 
  }

  public int render_source_queue_depth_max {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_render_source_queue_depth_max_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_render_source_queue_depth_max_get(swigCPtr);
      return ret;
    } 
  }

  public int render_source_initial_buffer_count {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_render_source_initial_buffer_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_render_source_initial_buffer_count_get(swigCPtr);
      return ret;
    } 
  }

  public int upstream_jitter_frame_count {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_upstream_jitter_frame_count_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_upstream_jitter_frame_count_get(swigCPtr);
      return ret;
    } 
  }

  public int allow_shared_capture_devices {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_allow_shared_capture_devices_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_allow_shared_capture_devices_get(swigCPtr);
      return ret;
    } 
  }

  public int max_logins_per_user {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_max_logins_per_user_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_max_logins_per_user_get(swigCPtr);
      return ret;
    } 
  }

  public string app_id {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_app_id_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_app_id_get(swigCPtr);
      return ret;
    } 
  }

  public string cert_data_dir {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_cert_data_dir_set(swigCPtr, value);
    } 
    get {
      string ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_cert_data_dir_get(swigCPtr);
      return ret;
    } 
  }

  public int reserved {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_reserved_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_reserved_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void job_queue_handle {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_job_queue_handle_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_sdk_config_t_job_queue_handle_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public long processor_affinity_mask {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_processor_affinity_mask_set(swigCPtr, value);
    } 
    get {
      long ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_processor_affinity_mask_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void callback_handle {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_callback_handle_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = VivoxCoreInstancePINVOKE.vx_sdk_config_t_callback_handle_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public vx_log_level initial_log_level {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_initial_log_level_set(swigCPtr, (int)value);
    } 
    get {
      vx_log_level ret = (vx_log_level)VivoxCoreInstancePINVOKE.vx_sdk_config_t_initial_log_level_get(swigCPtr);
      return ret;
    } 
  }

  public int disable_device_polling {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_disable_device_polling_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_disable_device_polling_get(swigCPtr);
      return ret;
    } 
  }

  public int force_capture_silence {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_force_capture_silence_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_force_capture_silence_get(swigCPtr);
      return ret;
    } 
  }

  public int enable_advanced_auto_levels {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_enable_advanced_auto_levels_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_enable_advanced_auto_levels_get(swigCPtr);
      return ret;
    } 
  }

  public int capture_device_buffer_size_intervals {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_capture_device_buffer_size_intervals_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_capture_device_buffer_size_intervals_get(swigCPtr);
      return ret;
    } 
  }

  public int render_device_buffer_size_intervals {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_render_device_buffer_size_intervals_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_render_device_buffer_size_intervals_get(swigCPtr);
      return ret;
    } 
  }

  public int disable_audio_ducking {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_disable_audio_ducking_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_disable_audio_ducking_get(swigCPtr);
      return ret;
    } 
  }

  public int use_access_tokens {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_use_access_tokens_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_use_access_tokens_get(swigCPtr);
      return ret;
    } 
  }

  public int enable_multiparty_text {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_enable_multiparty_text_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_enable_multiparty_text_get(swigCPtr);
      return ret;
    } 
  }

  public int enable_dtx {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_enable_dtx_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_enable_dtx_get(swigCPtr);
      return ret;
    } 
  }

  public uint default_codecs_mask {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_default_codecs_mask_set(swigCPtr, value);
    } 
    get {
      uint ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_default_codecs_mask_get(swigCPtr);
      return ret;
    } 
  }

  public int enable_fast_network_change_detection {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_enable_fast_network_change_detection_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_enable_fast_network_change_detection_get(swigCPtr);
      return ret;
    } 
  }

  public int use_os_proxy_settings {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_use_os_proxy_settings_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_use_os_proxy_settings_get(swigCPtr);
      return ret;
    } 
  }

  public int enable_persistent_http {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_enable_persistent_http_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_enable_persistent_http_get(swigCPtr);
      return ret;
    } 
  }

  public int preferred_sip_port {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_preferred_sip_port_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_preferred_sip_port_get(swigCPtr);
      return ret;
    } 
  }

  public int default_render_to_receiver {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_default_render_to_receiver_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_default_render_to_receiver_get(swigCPtr);
      return ret;
    } 
  }

  public float mic_makeup_gain {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_mic_makeup_gain_set(swigCPtr, value);
    } 
    get {
      float ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_mic_makeup_gain_get(swigCPtr);
      return ret;
    } 
  }

  public int dynamic_voice_processing_switching {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_dynamic_voice_processing_switching_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_dynamic_voice_processing_switching_get(swigCPtr);
      return ret;
    } 
  }

  public int never_rtp_timeout_ms {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_never_rtp_timeout_ms_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_never_rtp_timeout_ms_get(swigCPtr);
      return ret;
    } 
  }

  public int lost_rtp_timeout_ms {
    set {
      VivoxCoreInstancePINVOKE.vx_sdk_config_t_lost_rtp_timeout_ms_set(swigCPtr, value);
    } 
    get {
      int ret = VivoxCoreInstancePINVOKE.vx_sdk_config_t_lost_rtp_timeout_ms_get(swigCPtr);
      return ret;
    } 
  }

  public vx_sdk_config_t() : this(VivoxCoreInstancePINVOKE.new_vx_sdk_config_t(), true) {
  }

  public static readonly uint configSize = VivoxCoreInstancePINVOKE.vx_sdk_config_t_configSize_get();
}
